// <auto-generated />
using BrasGames.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrasGames.Migrations.ServiceDb
{
    [DbContext(typeof(ServiceDbContext))]
    [Migration("20240826103405_Fixing DbSet<ServiceTestModel>")]
    partial class FixingDbSetServiceTestModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("BrasGames.Model.ServiceTestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("serviceTestModels");
                });
#pragma warning restore 612, 618
        }
    }
}
