// <auto-generated />
using System;
using BrasGames.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrasGames.Migrations.ServiceDb
{
    [DbContext(typeof(ServiceDbContext))]
    [Migration("20240901133559_RemoveOrderLIstValitdationFromOrderModel")]
    partial class RemoveOrderLIstValitdationFromOrderModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("BrasGames.Model.ServiceModels.Console", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Price")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ReleaseYear")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Consoles");
                });

            modelBuilder.Entity("BrasGames.Model.ServiceModels.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgeRestriction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("BrasGames.Model.ServiceModels.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GovernmentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("orderState")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Controller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Controllers");
                });

            modelBuilder.Entity("BrasGames.Model.ServiceModels.Console", b =>
                {
                    b.HasOne("BrasGames.Model.ServiceModels.Order", null)
                        .WithMany("Consoles")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("BrasGames.Model.ServiceModels.Game", b =>
                {
                    b.HasOne("BrasGames.Model.ServiceModels.Order", null)
                        .WithMany("Games")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("Controller", b =>
                {
                    b.HasOne("BrasGames.Model.ServiceModels.Order", null)
                        .WithMany("Controllers")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("BrasGames.Model.ServiceModels.Order", b =>
                {
                    b.Navigation("Consoles");

                    b.Navigation("Controllers");

                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
