//Remove authorization if you are using cookies
// Service
    //Basic RESTAPI Requests

    //Controller
GET http://localhost:5103/service/controller/12
###
GET http://localhost:5103/service/controller/
###

    //Game
GET http://localhost:5103/service/game/1
###
GET http://localhost:5103/service/game/
###

    //Console
GET http://localhost:5103/service/console/3
###
GET http://localhost:5103/service/console/
###


// Business
    //DayStats
GET http://localhost:5103/business/agenda/4
###
GET http://localhost:5103/business/agenda/
###

    //Employee
GET http://localhost:5103/business/employee/4
###
GET http://localhost:5103/business/employee/
###
