// Service
    //Basic RESTAPI Requests

    //Controller
GET http://localhost:5103/service/controller/8
###
GET http://localhost:5103/service/controller/
###

    //Game
GET http://localhost:5103/service/game/1
###
GET http://localhost:5103/service/game/
###

    //Console
GET http://localhost:5103/service/console/3
###
GET http://localhost:5103/service/console/
###

    //Query Requests
    //Controllers
GET http://localhost:5103/service/controller/query/?nameSearch=Super&priceLowerBound=100&priceUpperBound=150
###
    //Games
    //Console

// Business
    //DayStats
GET http://localhost:5103/business/agenda/1
###
GET http://localhost:5103/business/agenda/
###

    //Employee
GET http://localhost:5103/business/employee/5
###
GET http://localhost:5103/business/employee/
###