//Remove authorization if you are using cookies
// Service
    //Basic RESTAPI Requests
    //Controller
DELETE http://localhost:5103/service/controller/13
###
DELETE http://localhost:5103/service/controller/
###

    //Game
DELETE http://localhost:5103/service/game/1
###
DELETE http://localhost:5103/service/game/
###

    //Console
DELETE http://localhost:5103/service/console/1
###
DELETE http://localhost:5103/service/console/
###

    //Query Requests
    //Controller
DELETE  http://localhost:5103/service/controller/query/?nameSearch=3
###    
    //Game
    //Console

// Business
    //DayStats
DELETE http://localhost:5103/business/agenda/2
###
DELETE http://localhost:5103/business/agenda/
###

    //Employee
DELETE http://localhost:5103/business/employee/4
###
DELETE http://localhost:5103/business/employee/
###