// Service
  //Controller
POST http://localhost:5103/service/controller/
Content-Type: application/json
Authorization: Bearer CfDJ8KjtqAG0WMBEohmF0s7ic65BgjcZIfkQy277x2DagukamGHHI22mYxUCYnItA-bemVPxeoTqrHWW2_Ryg8Hy-exUYRxxLNiuM5iocmCpxXkl01WjePAq6sQGLoaoV37S4DtLhN1uWc_8cn7BmIAZQiWS2J2EDBiovVQblpZAvRrWv0oNL1LYQEsHTC3mLqyKKP-5iYLZlxd14ShdcUee4e2DvnS117AXY7rRQwYThiR6vbmze1hplqbNkaV8j10KVkVQVI0GVCk6XPOCVtNW7MkLxxdilAHQtBdBOynsJiqArNhhVNRCfqqlnTd2dlGCvUnOb8w4k1BCSQ6JE-g4J2jiOfzf_VqXm93eeNlnTuSB9fK2B847V0d-JcMW1NU-OakgCoVKiLCZDFtPCS8KHmZQBEBhezCcF09wRUvoM0y6uq4sGhEvz_4OQo255OwK0Iv8gDU7rDUx-6f-IhyQx3WAO6umTKG3R9Q9pamvYtAaYWQVQbPxaOT011v6kmG9KO7T9N6FMwPzNxPVpbJKxNE6vluFuHYVlO8XrS0HgUctdxwhdU3hOo3pVLjGsbnFICBQOvnHgLyMYKYSNStuDOhxKNPvu1IGJmt-dBQtd-EE7j2ej_h-JAxIc9slRF23hmh0zyn5r3fUboF_oWXYx9H8nnBKkxIjGctg_3T94cdNbRgBWtn8eHPiP6gI1kJZng

{
  "name": "CONTROOOOLLLEERR 6",
  "type": "SpaceShipController",
  "year": 2100,
  "price": 2000
}
###
  //Game
  POST http://localhost:5103/service/game/
Content-Type: application/json

{
  "name": "DTO Game",
  "ageRestriction": "18+",
  "genre": "Puzzle",
  "price": 420.69
}
###


  //Console
  POST http://localhost:5103/service/console/
Content-Type: application/json

{
  "name": "Mega Console DTO",
  "type": "Handheld",
  "releaseYear": "2023-01-01",
  "price": 299.99
}
###
// Business
  //DayStats
  POST http://localhost:5103/business/agenda/
Content-Type: application/json

{
  "day": "2023-08-31",
  "totalConsumers": 1000,
  "totalProfit": 1000,
  "totalCost": 1000
}
###
  //Employee
  POST http://localhost:5103/business/employee/
Content-Type: application/json

{
  "name": "Dondale Dingle",
  "password": "dondaledingle123!",
  "email": "dondledingle@example.com",
  "age": 69,
  "yearsWorked": 420,
  "sex": 1,
  "isFired": true,
  "endOfContract": "2100-08-31",
  "salary": 69420.00
}
###