// Service
POST http://localhost:5103/service/controller/
Content-Type: application/json

{
  "name": "I hope this works",
  "type": "Type gratitude to God",
  "price": 777.77,
  "year": 3773
}
###

// Business
