// Service
  //Controller
POST http://localhost:5103/service/controller/
Content-Type: application/json

{
  "name": "CONTROOOOLLLEERR 6",
  "type": "SpaceShipController",
  "year": 2100,
  "price": 2000
}
###
  //Game
  POST http://localhost:5103/service/game/
Content-Type: application/json

{
  "name": "DTO Game",
  "ageRestriction": "18+",
  "genre": "Puzzle",
  "price": 420.69
}
###


  //Console
  POST http://localhost:5103/service/console/
Content-Type: application/json

{
  "name": "Mega Console DTO",
  "type": "Handheld",
  "releaseYear": "2023-01-01",
  "price": 299.99
}
###
// Business
  //DayStats
  POST http://localhost:5103/business/agenda/
Content-Type: application/json

{
  "day": "2023-08-31",
  "totalConsumers": 1000,
  "totalProfit": 1000,
  "totalCost": 1000
}
###
  //Employee
  POST http://localhost:5103/business/employee/
Content-Type: application/json

{
  "name": "Dondale Dingle",
  "password": "dondaledingle123!",
  "email": "dondledingle@example.com",
  "age": 69,
  "yearsWorked": 420,
  "sex": 1,
  "isFired": true,
  "endOfContract": "2100-08-31",
  "salary": 69420.00
}
###